"""Initial database schema

Revision ID: 001_initial_schema
Revises: 
Create Date: 2026-04-13 23:58:00.000000

This migration captures the initial database schema with all tables:
- users: Authentication and user management
- products: Inventory with pharmaceutical fields (INVIMA, laboratorio, etc)
- suppliers: Vendor information for purchase orders
- purchase_orders: Purchase order headers (DRAFT, CONFIRMED states)
- purchase_order_details: Individual items in purchase orders
- transactions: Financial transactions (sales, purchases, returns)

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('suppliers',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('nit', sa.String(), nullable=False),
    sa.Column('nombre_comercial', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nit')
    )
    op.create_table('products',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('codigo_barras', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('precio_compra', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('precio_venta', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('stock_actual', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('unidades_por_caja', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('registro_invima', sa.String(), nullable=True),
    sa.Column('principio_activo', sa.String(), nullable=True),
    sa.Column('estado_invima', sa.String(), nullable=True),
    sa.Column('laboratorio', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_barras')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('supplier_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('numero_factura', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order_details',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('purchase_order_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('producto_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('nombre_factura', sa.String(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('producto_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('usuario_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('purchase_order_details')
    op.drop_table('purchase_orders')
    op.drop_table('products')
    op.drop_table('suppliers')
    op.drop_table('users')
    # ### end Alembic commands ###
